namespace DerailValleyPlanner.Configs.Yard;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType=true)]
[XmlRoot(ElementName = "planner", Namespace="", IsNullable=false)]
public class Config {
    
    private List<DesignatorConfig> _designatorsField;
    
    private List<YardConfig> _yardsField;
    
    /// <remarks/>
    [XmlElement("designator")]
    public List<DesignatorConfig> Designators {
        get => _designatorsField;
        set => _designatorsField = value;
    }
    
    /// <remarks/>
    [XmlElement("yard")]
    public List<YardConfig> Yards {
        get => _yardsField;
        set => _yardsField = value;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType=true)]
public class DesignatorConfig {
    
    private string _nameField;
    
    private string _codeField;
    
    private string _valueField;
    
    /// <remarks/>
    [XmlAttribute("name")]
    public string Name {
        get => _nameField;
        set => _nameField = value;
    }
    
    /// <remarks/>
    [XmlAttribute("code")]
    public string Code {
        get => _codeField;
        set => _codeField = value;
    }
    
    /// <remarks/>
    [XmlText()]
    public string Value {
        get => _valueField;
        set => _valueField = value;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType=true)]
public class YardConfig {
    
    private List<YardDirectionConfig> _directionsField;
    
    private List<YardGroupConfig> _groupsField;
    
    private string _nameField;
    
    private string _codeField;
    private string _colorField;
    
    /// <remarks/>
    [XmlElement("direction")]
    public List<YardDirectionConfig> Directions {
        get => _directionsField;
        set => _directionsField = value;
    }
    
    /// <remarks/>
    [XmlElement("group")]
    public List<YardGroupConfig> Groups {
        get => _groupsField;
        set => _groupsField = value;
    }
    
    /// <remarks/>
    [XmlAttribute("name")]
    public string Name {
        get => _nameField;
        set => _nameField = value;
    }
    
    /// <remarks/>
    [XmlAttribute("code")]
    public string Code {
        get => _codeField;
        set => _codeField = value;
    }
    
    /// <remarks/>
    [XmlAttribute("color")]
    public string Color {
        get => _colorField;
        set => _colorField = value;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType=true)]
public class YardDirectionConfig {
    
    private string _typeField;
    
    private string _valueField;
    
    /// <remarks/>
    [XmlAttribute("type")]
    public string Type {
        get => _typeField;
        set => _typeField = value;
    }
    
    /// <remarks/>
    [XmlText()]
    public string Value {
        get => _valueField;
        set => _valueField = value;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType=true)]
public class YardGroupConfig {
    
    private string _noteField;
    
    private List<YardGroupTrackConfig> _tracksField;
    
    private string _nameField;
    
    private string _codeField;
    
    /// <remarks/>
    public string Note {
        get => _noteField;
        set => _noteField = value;
    }
    
    /// <remarks/>
    [XmlElement("track")]
    public List<YardGroupTrackConfig> Tracks {
        get => _tracksField;
        set => _tracksField = value;
    }
    
    /// <remarks/>
    [XmlAttribute("name")]
    public string Name {
        get => _nameField;
        set => _nameField = value;
    }
    
    /// <remarks/>
    [XmlAttribute("code")]
    public string Code {
        get => _codeField;
        set => _codeField = value;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType=true)]
public class YardGroupTrackConfig {
    
    private string _noteField;
    
    private List<string> _textField;
    
    private sbyte _idField;
    
    private bool _idFieldSpecified;
    
    private string _typeField;
    
    private string _directionField;
    
    /// <remarks/>
    public string Note {
        get => _noteField;
        set => _noteField = value;
    }
    
    /// <remarks/>
    [XmlText()]
    public List<string> Text {
        get => _textField;
        set => _textField = value;
    }
    
    /// <remarks/>
    [XmlAttribute("id")]
    public sbyte Id {
        get => _idField;
        set => _idField = value;
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool IdSpecified {
        get => _idFieldSpecified;
        set => _idFieldSpecified = value;
    }
    
    /// <remarks/>
    [XmlAttribute("type")]
    public string Type {
        get => _typeField;
        set => _typeField = value;
    }
    
    /// <remarks/>
    [XmlAttribute("direction")]
    public string Direction {
        get => _directionField;
        set => _directionField = value;
    }
}
