namespace DerailValleyPlanner.Configs.Yard;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType=true)]
[XmlRoot(ElementName = "planner", Namespace="", IsNullable=false)]
public class Config {
    
    private DesignatorConfig[] _designatorField;
    
    private YardConfig[] _yardField;
    
    /// <remarks/>
    [XmlElement("designator")]
    public DesignatorConfig[] Designator {
        get => _designatorField;
        set => _designatorField = value;
    }
    
    /// <remarks/>
    [XmlElement("yard")]
    public YardConfig[] Yard {
        get => _yardField;
        set => _yardField = value;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType=true)]
public class DesignatorConfig {
    
    private string _nameField;
    
    private string _codeField;
    
    private string _valueField;
    
    /// <remarks/>
    [XmlAttribute()]
    public string Name {
        get => _nameField;
        set => _nameField = value;
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string Code {
        get => _codeField;
        set => _codeField = value;
    }
    
    /// <remarks/>
    [XmlText()]
    public string Value {
        get => _valueField;
        set => _valueField = value;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType=true)]
public class YardConfig {
    
    private YardDirectionConfig[] _directionField;
    
    private YardGroupConfig[] _groupField;
    
    private string _nameField;
    
    private string _codeField;
    
    /// <remarks/>
    [XmlElement("direction")]
    public YardDirectionConfig[] Direction {
        get => _directionField;
        set => _directionField = value;
    }
    
    /// <remarks/>
    [XmlElement("group")]
    public YardGroupConfig[] Group {
        get => _groupField;
        set => _groupField = value;
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string Name {
        get => _nameField;
        set => _nameField = value;
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string Code {
        get => _codeField;
        set => _codeField = value;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType=true)]
public class YardDirectionConfig {
    
    private string _typeField;
    
    private string _valueField;
    
    /// <remarks/>
    [XmlAttribute()]
    public string Type {
        get => _typeField;
        set => _typeField = value;
    }
    
    /// <remarks/>
    [XmlText()]
    public string Value {
        get => _valueField;
        set => _valueField = value;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType=true)]
public class YardGroupConfig {
    
    private string _noteField;
    
    private YardGroupTrackConfig[] _trackField;
    
    private string _nameField;
    
    private string _codeField;
    
    /// <remarks/>
    public string Note {
        get => _noteField;
        set => _noteField = value;
    }
    
    /// <remarks/>
    [XmlElement("track")]
    public YardGroupTrackConfig[] Track {
        get => _trackField;
        set => _trackField = value;
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string Name {
        get => _nameField;
        set => _nameField = value;
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string Code {
        get => _codeField;
        set => _codeField = value;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType=true)]
public class YardGroupTrackConfig {
    
    private string _noteField;
    
    private string[] _textField;
    
    private sbyte _idField;
    
    private bool _idFieldSpecified;
    
    private string _typeField;
    
    private string _directionField;
    
    /// <remarks/>
    public string Note {
        get => _noteField;
        set => _noteField = value;
    }
    
    /// <remarks/>
    [XmlText()]
    public string[] Text {
        get => _textField;
        set => _textField = value;
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public sbyte Id {
        get => _idField;
        set => _idField = value;
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool IdSpecified {
        get => _idFieldSpecified;
        set => _idFieldSpecified = value;
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string Type {
        get => _typeField;
        set => _typeField = value;
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string Direction {
        get => _directionField;
        set => _directionField = value;
    }
}
