# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build & Generate Artifact

on:
  push:
    branches: [ "master" ]
  release:
    types:
      - published

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install .NET Maui
        run: dotnet workload install maui-windows

#      - name: Restore NuGet packages
#        run: dotnet restore ${{ env.PROJECT_PATH }} --ignore-failed-sources
      - name: Build
        run: dotnet build DerailValleyPlanner/DerailValleyPlanner.csproj -c Release -f net7.0-windows10.0.19041.0
        
      - name: Debug
        run: tree

      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: Derail Valley Planner (Portable)
          path: ./DerailValleyPlanner/bin/**/win10-x64/**/*.*
